# MarketStore配置文件示例 - 币安数据源插件V2
root_directory: data
listen_port: 5993
log_level: info
timezone: UTC

# 后台工作器配置
bgworkers:
  - module: binancefeeder_v2.so
    name: BinanceFeederV2
    config:
      # API配置
      api_key: "your_binance_api_key_here"
      secret_key: "your_binance_secret_key_here"
      testnet: false  # 设置为true使用测试网

      # 符号配置
      symbols:
        - "BTCUSDT"
        - "ETHUSDT"
        - "BNBUSDT"
        - "ADAUSDT"
        - "SOLUSDT"
        - "DOTUSDT"
        - "AVAXUSDT"
        - "MATICUSDT"
        - "LINKUSDT"
        - "UNIUSDT"
      
      # 排除的符号（可选）
      exclude_symbols:
        - "BTTUSDT"
        - "SHIBUSDT"

      # 时间框架配置
      timeframe: "1m"  # 基础时间框架

      # Backfill配置
      backfill:
        enabled: true
        start_time: "2024-01-01T00:00:00Z"
        end_time: "2024-01-31T23:59:59Z"
        batch_size: 1000
        parallelism: 5
        interval: "1m"  # 数据间隔

      # 实时数据配置
      realtime:
        enabled: true
        stream_type: "kline"  # kline, trade, depth
        update_freq: "1m"     # 更新频率
        buffer_size: 1000     # 缓冲区大小
        max_retries: 3        # 最大重试次数
        retry_delay: "5s"     # 重试延迟

# 触发器配置（可选）
triggers:
  - module: ondiskagg.so
    on: "*/1m/OHLCV"
    config:
      filter: "*/1m/OHLCV"
      destination: "*/5m/OHLCV"
      aggfunc: "sum"
      aggfunc_params:
        - "Volume"
      aggfunc_returns:
        - "Volume"
      dest_timeframe: "5m"
      dest_attrgroup: "OHLCV" 